version: '3.9'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    ports:
      - '5432:5432'
    volumes:
      - ./dbdata:/var/lib/postgresql/data
